server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
      settings: 
        web-allow-others: true  	
  jpa: 
    hibernate: 
      ddl-auto: update 
fussballmanager:
  admin:
    login: admin
    password: blub